# Generated by Django 4.0 on 2022-02-09 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_alter_pet_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='image_url',
            new_name='image',
        ),
    ]
