# Generated by Django 4.0 on 2022-03-20 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_pet_user_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
